import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const rpcUrl = process.env.HARMONY_RPC_URL;
if (!rpcUrl) {
  throw new Error('HARMONY_RPC_URL is required. Do not expose it as a VITE_* variable.');
}

async function rpc(method) {
  const response = await fetch(rpcUrl, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ jsonrpc: '2.0', id: method, method, params: [] }),
  });
  if (!response.ok) throw new Error(`RPC ${method} failed with HTTP ${response.status}.`);
  const payload = await response.json();
  if (payload.error) throw new Error(`RPC ${method} failed: ${payload.error.message}`);
  return payload.result;
}

const [chainIdHex, blockNumberHex] = await Promise.all([rpc('eth_chainId'), rpc('eth_blockNumber')]);
const snapshot = {
  schemaVersion: '1.0.0',
  generatedAt: new Date().toISOString(),
  source: 'Configured Harmony RPC endpoint',
  network: {
    namespace: 'eip155',
    chainId: Number.parseInt(chainIdHex, 16),
    latestObservedBlock: Number.parseInt(blockNumberHex, 16).toString(),
  },
  notes: ['Generated by scripts/fixtures/refresh-harmony.mjs.', 'Review and validate before publication.'],
};
const serialized = `${JSON.stringify(snapshot, null, 2)}\n`;
const checksum = createHash('sha256').update(serialized).digest('hex');

if (process.argv.includes('--write')) {
  const destination = resolve('src/mocks/fixtures/harmony-network-snapshot.json');
  await writeFile(destination, serialized, 'utf8');
  await writeFile(`${destination}.sha256`, `${checksum}  harmony-network-snapshot.json\n`, 'utf8');
  process.stdout.write(`Snapshot written. sha256:${checksum}\n`);
} else {
  process.stdout.write(serialized);
  process.stderr.write(`Dry run only. sha256:${checksum}. Pass --write after editorial review.\n`);
}
