export const queryKeys = {
  investigations: (query = '') => ['investigations', query] as const,
  investigation: (slug: string) => ['investigation', slug] as const,
  evidenceList: (query = '') => ['evidence', query] as const,
  evidence: (id: string) => ['evidence-detail', id] as const,
  evidenceLineage: (id: string) => ['evidence-lineage', id] as const,
  researchList: (query = '') => ['research', query] as const,
  research: (slug: string) => ['research-detail', slug] as const,
  entities: (query = '') => ['entities', query] as const,
  entity: (id: string) => ['entity', id] as const,
  relationships: (id: string) => ['entity-relationships', id] as const,
  networks: ['networks'] as const,
  network: (slug: string) => ['network', slug] as const,
  submissions: ['submissions'] as const,
  submission: (id: string) => ['submission', id] as const,
  search: (query: string) => ['search', query] as const,
  session: ['auth-session'] as const,
  adminDashboard: ['admin-dashboard'] as const,
  adminUsers: ['admin-users'] as const,
};
