import { PageHeader } from '@/components/shared/page-header';
import { AssessmentBadge, ClaimKindBadge, IntegrityBadge, VerificationBadge } from '@/components/ui/badges';
import { Button } from '@/components/ui/button';
import { Card, DataPanel } from '@/components/ui/card';

export function DesignSystemPage() {
  if (import.meta.env.PROD) return null;
  return <div className="tic-page"><PageHeader eyebrow="System" title="Design System" description="Implementation reference for tokens, states, semantics, and responsive behavior." /><div className="tic-stack"><DataPanel><div className="tic-section-heading"><div><p className="tic-eyebrow">Actions</p><h2>Buttons</h2></div></div><div className="tic-inline-actions"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Danger</Button><Button loading>Loading</Button></div></DataPanel><DataPanel><div className="tic-section-heading"><div><p className="tic-eyebrow">Claims only</p><h2>Epistemic assessment</h2></div></div><div className="tic-badge-row">{(['confirmed', 'strongly_supported', 'probable', 'possible', 'undetermined'] as const).map((value) => <AssessmentBadge key={value} assessment={value} />)}</div><div className="tic-badge-row" style={{ marginTop: 'var(--tic-space-md)' }}>{(['fact', 'inference', 'hypothesis', 'opinion'] as const).map((value) => <ClaimKindBadge key={value} kind={value} />)}</div></DataPanel><DataPanel><div className="tic-section-heading"><div><p className="tic-eyebrow">Evidence only</p><h2>Verification and integrity</h2></div></div><div className="tic-badge-row">{(['verified', 'partially_verified', 'unverified'] as const).map((value) => <VerificationBadge key={value} status={value} />)}</div><div className="tic-badge-row" style={{ marginTop: 'var(--tic-space-md)' }}>{(['intact', 'unknown', 'disputed'] as const).map((value) => <IntegrityBadge key={value} status={value} />)}</div></DataPanel><div className="tic-grid tic-grid--3"><Card><h3>Loading</h3><p className="tic-muted">Skeleton and contextual status patterns replace global spinners.</p></Card><Card><h3>Empty</h3><p className="tic-muted">Empty states explain what is absent and what can happen next.</p></Card><Card><h3>Error</h3><p className="tic-muted">Errors preserve route context and offer recovery where possible.</p></Card></div></div></div>;
}
